apiVersion: v1
kind: Service
metadata:
    name: "smk8scluster2-b56a"
    labels:
        app: "smk8scluster2-b56a"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "smk8scluster2-b56a"